### ISSUE TITLE
可以画弧线吗？

### ISSUE THREAD

**Issue by iamnotblank** [john-keith/THREE-FlyLine#3]

**Comment by john-keith** [comment]
curve类就是给你画弧线用的啊

**Comment by iamnotblank** [comment]
> curve类就是给你画弧线用的啊

我用 SplineCurve3 画了一条线，作为第一个入参；结果是几节小点，不动的

`
var curve = new THREE.SplineCurve3([
                    new THREE.Vector3(-10, 10, 10),
                    new THREE.Vector3(-5, 5, 5),
                    new THREE.Vector3(0, 0, 0),
                    new THREE.Vector3(5, -5, 5),
                    new THREE.Vector3(10, 0, 10), 
                ])
`

**Comment by john-keith** [comment]
样例代码里不是写了么

**Comment by iamnotblank** [comment]
你换成我那个图形试试，飞线不动
